apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitrello.fullname" . }}
  labels:
    {{- include "gitrello.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "gitrello.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "gitrello.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gitrello.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "fnsdev/gitrello:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: django_secret_key
            - name: DJANGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: django_db_name
            - name: DJANGO_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: django_db_user
            - name: DJANGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: django_db_password
            - name: DJANGO_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: django_db_host
            - name: DJANGO_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: django_db_port
            - name: EMAIL_HOST_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: email_host_user
            - name: EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: email_host_password
            - name: GS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: gs_bucket_name
            - name: GS_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: gs_credentials
            - name: GS_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: gs_project_id
            - name: URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: url
            - name: GITHUB_INTEGRATION_SERVICE_URL
              valueFrom:
               secretKeyRef:
                 name: {{ .Values.secret.name }}
                 key: github_integration_service_url
            - name: GITHUB_CLIENT_ID
              valueFrom:
               secretKeyRef:
                 name: {{ .Values.secret.name }}
                 key: github_client_id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
               secretKeyRef:
                 name: {{ .Values.secret.name }}
                 key: github_client_secret
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
